"""Curated catalogue for the Gbena Grant movie app.

Single source of truth: the artwork generator and the TypeScript data module are
both emitted from this list so nothing can drift out of sync.
"""

# id, title, year, runtime_min, rating, votes, genres, director, cast, tagline, synopsis, featured, badge
MOVIES = [
    ("shawshank", "The Shawshank Redemption", 1994, 142, 9.3, "2.9M", ["Drama"],
     "Frank Darabont", ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
     "Fear can hold you prisoner. Hope can set you free.",
     "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", True, "All-time #1"),
    ("godfather", "The Godfather", 1972, 175, 9.2, "2.1M", ["Crime", "Drama"],
     "Francis Ford Coppola", ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"],
     "An offer you can't refuse.",
     "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", True, "Oscar Winner"),
    ("dark-knight", "The Dark Knight", 2008, 152, 9.0, "2.9M", ["Action", "Crime"],
     "Christopher Nolan", ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Maggie Gyllenhaal"],
     "Why so serious?",
     "Batman raises the stakes in his war on crime as the Joker plunges Gotham into anarchy and tests every hero's resolve.", True, "Oscar Winner"),
    ("pulp-fiction", "Pulp Fiction", 1994, 154, 8.9, "2.2M", ["Crime", "Thriller"],
     "Quentin Tarantino", ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis"],
     "Girls like me don't make invitations like this to just anyone.",
     "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.", False, "Palme d'Or"),
    ("inception", "Inception", 2010, 148, 8.8, "2.5M", ["Sci-Fi", "Action"],
     "Christopher Nolan", ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
     "Your mind is the scene of the crime.",
     "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.", True, "4 Oscars"),
    ("interstellar", "Interstellar", 2014, 169, 8.7, "2.1M", ["Sci-Fi", "Drama"],
     "Christopher Nolan", ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
     "Mankind was born on Earth. It was never meant to die here.",
     "Explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", True, ""),
    ("parasite", "Parasite", 2019, 132, 8.5, "950K", ["Thriller", "Drama"],
     "Bong Joon-ho", ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
     "Act like you own the place.",
     "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", True, "Best Picture"),
    ("spirited-away", "Spirited Away", 2001, 125, 8.6, "830K", ["Animation", "Fantasy"],
     "Hayao Miyazaki", ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki", "Takashi Naito"],
     "Not every spirit is kind.",
     "During her family's move to the suburbs, a sullen ten-year-old girl wanders into a world ruled by gods, witches and spirits.", False, "Oscar Winner"),
    ("matrix", "The Matrix", 1999, 136, 8.7, "2.0M", ["Sci-Fi", "Action"],
     "The Wachowskis", ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
     "Free your mind.",
     "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", True, ""),
    ("goodfellas", "Goodfellas", 1990, 145, 8.7, "1.3M", ["Crime", "Drama"],
     "Martin Scorsese", ["Robert De Niro", "Ray Liotta", "Joe Pesci", "Lorraine Bracco"],
     "Three decades of life in the mafia.",
     "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen and his partners Jimmy Conway and Tommy DeVito.", False, ""),
    ("fight-club", "Fight Club", 1999, 139, 8.8, "2.3M", ["Drama", "Thriller"],
     "David Fincher", ["Brad Pitt", "Edward Norton", "Helena Bonham Carter", "Meat Loaf"],
     "Mischief. Mayhem. Soap.",
     "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something far larger.", False, "Cult Classic"),
    ("forrest-gump", "Forrest Gump", 1994, 142, 8.8, "2.2M", ["Drama", "Romance"],
     "Robert Zemeckis", ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
     "Life is like a box of chocolates.",
     "The presidencies of Kennedy and Johnson, the Vietnam War and Watergate unfold through the eyes of an Alabama man with an IQ of 75.", False, "Best Picture"),
    ("fellowship", "The Lord of the Rings: The Fellowship of the Ring", 2001, 178, 8.9, "2.0M", ["Fantasy", "Adventure"],
     "Peter Jackson", ["Elijah Wood", "Ian McKellen", "Viggo Mortensen", "Cate Blanchett"],
     "One ring to rule them all.",
     "A meek hobbit of the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth.", True, "4 Oscars"),
    ("gladiator", "Gladiator", 2000, 155, 8.5, "1.6M", ["Action", "Adventure"],
     "Ridley Scott", ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed"],
     "A hero will rise.",
     "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.", False, "Best Picture"),
    ("titanic", "Titanic", 1997, 194, 7.9, "1.3M", ["Romance", "Drama"],
     "James Cameron", ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates"],
     "Nothing on Earth could come between them.",
     "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", False, "11 Oscars"),
    ("schindlers-list", "Schindler's List", 1993, 195, 9.0, "1.5M", ["War", "Drama"],
     "Steven Spielberg", ["Liam Neeson", "Ralph Fiennes", "Ben Kingsley", "Caroline Goodall"],
     "Whoever saves one life, saves the world entire.",
     "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.", False, "Best Picture"),
    ("silence-lambs", "The Silence of the Lambs", 1991, 118, 8.6, "1.5M", ["Thriller", "Crime"],
     "Jonathan Demme", ["Jodie Foster", "Anthony Hopkins", "Scott Glenn", "Ted Levine"],
     "A lot can happen in the dark.",
     "A young FBI cadet must confide in an incarcerated and manipulative cannibal killer to receive help on another serial murder case.", False, "Big Five Oscars"),
    ("saving-private-ryan", "Saving Private Ryan", 1998, 169, 8.6, "1.5M", ["War", "Action"],
     "Steven Spielberg", ["Tom Hanks", "Matt Damon", "Tom Sizemore", "Edward Burns"],
     "The mission is a man.",
     "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.", False, "5 Oscars"),
    ("whiplash", "Whiplash", 2014, 106, 8.5, "1.1M", ["Drama", "Music"],
     "Damien Chazelle", ["Miles Teller", "J.K. Simmons", "Paul Reiser", "Melissa Benoist"],
     "The road to greatness can take you to the edge.",
     "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing.", True, "3 Oscars"),
    ("la-la-land", "La La Land", 2016, 128, 8.0, "700K", ["Romance", "Music"],
     "Damien Chazelle", ["Ryan Gosling", "Emma Stone", "John Legend", "Rosemarie DeWitt"],
     "Here's to the ones who dream.",
     "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations.", False, "6 Oscars"),
    ("mad-max", "Mad Max: Fury Road", 2015, 120, 8.1, "1.1M", ["Action", "Adventure"],
     "George Miller", ["Tom Hardy", "Charlize Theron", "Nicholas Hoult", "Hugh Keays-Byrne"],
     "What a lovely day.",
     "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners.", True, "6 Oscars"),
    ("everything-everywhere", "Everything Everywhere All at Once", 2022, 139, 7.8, "620K", ["Sci-Fi", "Comedy"],
     "Daniel Kwan, Daniel Scheinert", ["Michelle Yeoh", "Ke Huy Quan", "Stephanie Hsu", "Jamie Lee Curtis"],
     "The universe is so much bigger than you realize.",
     "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes.", True, "7 Oscars"),
    ("oppenheimer", "Oppenheimer", 2023, 180, 8.3, "830K", ["Drama", "History"],
     "Christopher Nolan", ["Cillian Murphy", "Emily Blunt", "Robert Downey Jr.", "Matt Damon"],
     "The world forever changes.",
     "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.", True, "7 Oscars"),
    ("dune-two", "Dune: Part Two", 2024, 167, 8.5, "560K", ["Sci-Fi", "Adventure"],
     "Denis Villeneuve", ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem"],
     "Long live the fighters.",
     "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.", True, "New Release"),
    ("spider-verse", "Spider-Man: Into the Spider-Verse", 2018, 117, 8.4, "700K", ["Animation", "Action"],
     "Peter Ramsey, Bob Persichetti, Rodney Rothman", ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld", "Mahershala Ali"],
     "Anyone can wear the mask.",
     "Teen Miles Morales becomes the Spider-Man of his reality and crosses paths with five counterparts from other dimensions.", False, "Oscar Winner"),
    ("coco", "Coco", 2017, 105, 8.4, "640K", ["Animation", "Fantasy"],
     "Lee Unkrich", ["Anthony Gonzalez", "Gael García Bernal", "Benjamin Bratt", "Alanna Ubach"],
     "The celebration of a lifetime.",
     "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather.", False, "2 Oscars"),
    ("get-out", "Get Out", 2017, 104, 7.8, "700K", ["Horror", "Thriller"],
     "Jordan Peele", ["Daniel Kaluuya", "Allison Williams", "Bradley Whitford", "Catherine Keener"],
     "Just because you're invited doesn't mean you're welcome.",
     "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness eventually reaches a boiling point.", False, "Oscar Winner"),
    ("moonlight", "Moonlight", 2016, 111, 7.4, "480K", ["Drama"],
     "Barry Jenkins", ["Mahershala Ali", "Naomie Harris", "Trevante Rhodes", "André Holland"],
     "This is the story of a lifetime.",
     "A young Black man growing up in Miami finds his identity across three defining chapters of his life.", False, "Best Picture"),
    ("grand-budapest", "The Grand Budapest Hotel", 2014, 99, 8.1, "900K", ["Comedy", "Adventure"],
     "Wes Anderson", ["Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric", "Adrien Brody"],
     "A perfect holiday, a perfect crime.",
     "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy and his adventures with a legendary concierge.", False, "4 Oscars"),
    ("joker", "Joker", 2019, 122, 8.4, "1.4M", ["Thriller", "Crime"],
     "Todd Phillips", ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz", "Frances Conroy"],
     "Put on a happy face.",
     "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society, then begins a slow descent into madness.", True, "2 Oscars"),
    ("blade-runner-2049", "Blade Runner 2049", 2017, 164, 8.0, "700K", ["Sci-Fi", "Thriller"],
     "Denis Villeneuve", ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Sylvia Hoeks"],
     "The key to the future is finally unearthed.",
     "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.", False, "2 Oscars"),
    ("arrival", "Arrival", 2016, 116, 7.9, "730K", ["Sci-Fi", "Drama"],
     "Denis Villeneuve", ["Amy Adams", "Jeremy Renner", "Forest Whitaker", "Michael Stuhlbarg"],
     "Why are they here?",
     "A linguist is recruited by the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.", False, "Oscar Winner"),
    ("prestige", "The Prestige", 2006, 130, 8.5, "1.5M", ["Thriller", "Drama"],
     "Christopher Nolan", ["Hugh Jackman", "Christian Bale", "Michael Caine", "Scarlett Johansson"],
     "Are you watching closely?",
     "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything to outwit each other.", True, ""),
    ("django", "Django Unchained", 2012, 165, 8.5, "1.7M", ["Western", "Action"],
     "Quentin Tarantino", ["Jamie Foxx", "Christoph Waltz", "Leonardo DiCaprio", "Samuel L. Jackson"],
     "Life, liberty and the pursuit of vengeance.",
     "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.", False, "2 Oscars"),
    ("casablanca", "Casablanca", 1942, 102, 8.5, "620K", ["Romance", "Drama"],
     "Michael Curtiz", ["Humphrey Bogart", "Ingrid Bergman", "Paul Henreid", "Claude Rains"],
     "As big a star as ever shone on a screen.",
     "A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis.", False, "Best Picture"),
    ("psycho", "Psycho", 1960, 109, 8.5, "700K", ["Horror", "Thriller"],
     "Alfred Hitchcock", ["Anthony Perkins", "Janet Leigh", "Vera Miles", "John Gavin"],
     "A new dimension of terror.",
     "A Phoenix secretary embezzles money, goes on the run and checks into a remote motel run by a young man under the domination of his mother.", False, "Masterpiece"),
    ("alien", "Alien", 1979, 117, 8.5, "920K", ["Horror", "Sci-Fi"],
     "Ridley Scott", ["Sigourney Weaver", "Tom Skerritt", "John Hurt", "Veronica Cartwright"],
     "In space no one can hear you scream.",
     "The crew of a commercial spacecraft encounters a deadly lifeform after investigating an unknown transmission.", False, "Oscar Winner"),
    ("ratatouille", "Ratatouille", 2007, 111, 8.1, "830K", ["Animation", "Comedy"],
     "Brad Bird", ["Patton Oswalt", "Ian Holm", "Lou Romano", "Janeane Garofalo"],
     "He's dying to become a chef.",
     "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous restaurant.", False, "Oscar Winner"),
    ("endgame", "Avengers: Endgame", 2019, 181, 8.4, "1.2M", ["Action", "Adventure"],
     "Anthony Russo, Joe Russo", ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Scarlett Johansson"],
     "Whatever it takes.",
     "After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos' actions and restore balance to the universe.", True, "Box Office Record"),
    ("john-wick", "John Wick", 2014, 101, 7.4, "700K", ["Action", "Thriller"],
     "Chad Stahelski", ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen", "Willem Dafoe"],
     "Don't set him off.",
     "An ex-hit-man comes out of retirement to track down the gangsters who killed his dog and took everything from him.", False, ""),

    # --- Nollywood selection ---
    ("lionheart", "Lionheart", 2018, 95, 6.9, "3.1K", ["Nollywood", "Drama"],
     "Genevieve Nnaji", ["Genevieve Nnaji", "Nnamdi Asomugha", "Pete Edochie", "Odalys García"],
     "A daughter. A business. A fight.",
     "When her father falls ill, Adaeze must step up to run the family transport company and prove herself in a world that doubts her.", True, "Netflix Original"),
    ("milkmaid", "The Milkmaid", 2020, 96, 6.5, "1.2K", ["Nollywood", "Drama"],
     "Desmond Ovbiagele", ["Anthonieta Kalunta", "Gambo Usman Kona", "Mary Booth", "Yakubu Mohammed"],
     "Her fight. Her freedom.",
     "A Fulani milkmaid searches for her missing sister amid insurgency, trafficking and a shifting loyalty to a rebel commander.", False, "Nigeria Oscar Entry"),
    ("king-of-boys", "King of Boys", 2018, 182, 7.0, "2.4K", ["Nollywood", "Crime"],
     "Kemi Adetiba", ["Sola Sobowale", "Adesua Etomi", "Reminisce Safianu", "Illblu Tobechukwu"],
     "Power has a price.",
     "A powerful businesswoman and philanthropist's political ambition puts her at war with the very underworld that made her.", True, ""),
    ("oloture", "Òlòtūré", 2019, 106, 6.4, "1.8K", ["Nollywood", "Crime"],
     "Kenneth Gyang", ["Segun Arinze", "Omotola Jalade-Ekeinde", "Blossom Chukwujekwu", "Gregory Ojefua"],
     "The truth is never for sale.",
     "An undercover journalist risks everything to expose the trafficking networks operating in the heart of Lagos.", False, ""),
    ("seventy-six", "76", 2016, 110, 7.0, "1.5K", ["Nollywood", "War"],
     "Izu Ojukwu", ["Ramsey Nouah", "Rita Dominic", "Chidi Mokeme", "Ibinabo Fiberesima"],
     "A love story in a time of war.",
     "Set six years after the civil war, a young officer from the Middle Belt falls in love with an O-level student from the South East.", False, "AMVCA Winner"),
    ("wedding-party", "The Wedding Party", 2016, 100, 6.5, "2.0K", ["Nollywood", "Comedy"],
     "Kemi Adetiba", ["Sola Sobowale", "Adesua Etomi", "Banky Wellington", "Zynnell Zuh"],
     "Two families. One wedding. Total chaos.",
     "A destination wedding in Lagos brings together two wildly different families for a weekend of secrets, drama and celebration.", True, "Box Office Hit"),
    ("anikulapo", "Anikulapo", 2022, 106, 6.2, "1.1K", ["Nollywood", "Fantasy"],
     "Kunle Afolayan", ["Kunle Remi", "Bimbo Ademoye", "Lateef Adedimeji", "Sola Sobowale"],
     "Death has a price.",
     "A wandering minstrel's affair with a king's wife draws him into a bargain with the keeper of the underworld.", False, ""),
    ("jagun-jagun", "Jagun Jagun: The Warrior", 2023, 103, 6.0, "1.4K", ["Nollywood", "Action"],
     "Adebayo Tijani, Tope Adebayo", ["Lateef Adedimeji", "Fathia Balogun", "Bimbo Ademoye", "Muyiwa Ademola"],
     "The army that never loses.",
     "A young man hungry for power joins an elite army of warriors, only to face a commander feared by gods and men.", True, "Netflix Original"),
    ("breath-of-life", "Breath of Life", 2023, 107, 6.8, "900", ["Nollywood", "Drama"],
     "B.B. Daniel", ["Wale Ojo", "Genoveva Umeh", "Chimezie Imo", "Tina Mba"],
     "One night. One chance. One breath.",
     "A grieving man plans to end his life on a specific night, until an unexpected visitor forces him to confront everything he lost.", False, "AMVCA Best Film"),
    ("tribe-called-judah", "A Tribe Called Judah", 2023, 122, 6.3, "1.3K", ["Nollywood", "Comedy"],
     "Funke Akindele", ["Funke Akindele", "Timini Egbuson", "Uzor Arukwe", "Nse Ikpe-Etim"],
     "Family is a full-time job.",
     "A devoted single mother's three sons from different fathers must band together to save her from a life-threatening illness.", True, "Highest Grossing"),
]

GENRE_ORDER = [
    "Trending", "Nollywood", "Action", "Drama", "Sci-Fi", "Crime", "Thriller",
    "Comedy", "Animation", "Romance", "Horror", "Adventure", "Fantasy", "War",
    "Western", "Music", "History",
]


def slug(text: str) -> str:
    keep = []
    for ch in text.lower():
        if ch.isalnum():
            keep.append(ch)
        elif ch in " -:" and (not keep or keep[-1] != "-"):
            keep.append("-")
    return "".join(keep).strip("-")


def as_dicts():
    out = []
    for (mid, title, year, runtime, rating, votes, genres, director, cast,
         tagline, synopsis, featured, badge) in MOVIES:
        out.append({
            "id": mid, "title": title, "year": year, "runtime": runtime,
            "rating": rating, "votes": votes, "genres": genres,
            "director": director, "cast": cast, "tagline": tagline,
            "synopsis": synopsis, "featured": featured, "badge": badge,
            "slug": slug(title),
        })
    return out
